build:
    project_setup:
        before:
            - cp .env.test .env
    nodes:
        analysis:
            project_setup:
                override:
                    - 'true'
            tests:
                override:
                    - php-scrutinizer-run
                    -
                        command: phpcs-run
                        use_website_config: true
filter:
    excluded_paths:
        - 'tests/*'
        - 'bin/*'
checks:
    php: true
coding_style:
    php: {  }
